package com.aaron.yqb.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.aaron.yqb.greendao.KlineModel;

import com.aaron.yqb.greendao.KlineModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig klineModelDaoConfig;

    private final KlineModelDao klineModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        klineModelDaoConfig = daoConfigMap.get(KlineModelDao.class).clone();
        klineModelDaoConfig.initIdentityScope(type);

        klineModelDao = new KlineModelDao(klineModelDaoConfig, this);

        registerDao(KlineModel.class, klineModelDao);
    }
    
    public void clear() {
        klineModelDaoConfig.getIdentityScope().clear();
    }

    public KlineModelDao getKlineModelDao() {
        return klineModelDao;
    }

}
