package com.aaron.yqb.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "KLINE_MODEL".
 */
public class KlineModel {

    private Long id;
    private Float openPrice;
    private Float maxPrice;
    private Float closePrice;
    private Float minPrice;
    private String instrumentID;
    private Integer volume;
    private String time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public KlineModel() {
    }

    public KlineModel(Long id) {
        this.id = id;
    }

    public KlineModel(Long id, Float openPrice, Float maxPrice, Float closePrice, Float minPrice, String instrumentID, Integer volume, String time) {
        this.id = id;
        this.openPrice = openPrice;
        this.maxPrice = maxPrice;
        this.closePrice = closePrice;
        this.minPrice = minPrice;
        this.instrumentID = instrumentID;
        this.volume = volume;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getOpenPrice() {
        return openPrice;
    }

    public void setOpenPrice(Float openPrice) {
        this.openPrice = openPrice;
    }

    public Float getMaxPrice() {
        return maxPrice;
    }

    public void setMaxPrice(Float maxPrice) {
        this.maxPrice = maxPrice;
    }

    public Float getClosePrice() {
        return closePrice;
    }

    public void setClosePrice(Float closePrice) {
        this.closePrice = closePrice;
    }

    public Float getMinPrice() {
        return minPrice;
    }

    public void setMinPrice(Float minPrice) {
        this.minPrice = minPrice;
    }

    public String getInstrumentID() {
        return instrumentID;
    }

    public void setInstrumentID(String instrumentID) {
        this.instrumentID = instrumentID;
    }

    public Integer getVolume() {
        return volume;
    }

    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
